#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  6              \
    bottom_padding               6              \
    left_padding                 6              \
    right_padding                6              \
    window_gap                   6              \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Set floating applications
yabai -m rule --add app="System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="Messages$" sticky=on layer=above manage=off
yabai -m rule --add app="System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="balenaEtcher$" sticky=on layer=above manage=off

# Specific app rules
yabai -m rule --add app="Godot$" title="Alert!$" sticky=on layer=above manage=off
yabai -m rule --add app="Godot$" title="Alert!$" sticky=on layer=above manage=off
yabai -m rule --add title="Alert!" sticky=on layer=above manage=off
yabai -m rule --add title="Alert!$" sticky=on layer=above manage=off

yabai -m signal --add event=window_created action='
  yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || \
  yabai -m window $YABAI_WINDOW_ID --toggle float && \
  yabai -m window $YABAI_WINDOW_ID --layer above && \
  yabai -m window $YABAI_WINDOW_ID --grid 3:3:1:1:1:1
'

echo "yabai configuration loaded.."
